### ISSUE TITLE
拦截点能被加载到，但是拦截逻辑中出现NoClassDefFoundError

### ISSUE THREAD

**Issue by Zyh2333** [polarismesh/polaris-java-agent#11]
1. 拦截点：org.springframework.context.support.AbstractApplicationContext.refresh()
但是在仅dubbo环境中，报错如下：
java.lang.NoClassDefFoundError: org/springframework/web/context/support/GenericWebApplicationContext
	at cn.polarismesh.agent.core.spring.cloud.support.PolarisRegistryInterceptor.afterInterceptor(PolarisRegistryInterceptor.java:22) ~[polaris-agent-spring-cloud-2021-plugin-1.0.0-SNAPSHOT.jar:?]
	at cn.polarismesh.agent.adapter.spring.cloud.interceptor.PolarisRegistryInterceptor.after(PolarisRegistryInterceptor.java:23) ~[pinpoint-spring-cloud-2021-plugin-1.0.0-SNAPSHOT.jar:?]
	at com.navercorp.pinpoint.bootstrap.interceptor.ExceptionHandleAroundInterceptor.after(ExceptionHandleAroundInterceptor.java:44) [?:2.3.3]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:902) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95) [spring-context-5.2.12.RELEASE.jar:5.2.12.RELEASE]
2. 拦截点：com.netflix.loadbalancer.LoadBalancerContext.<init>
02-15 14:10:06.006 [           main] ERROR c.n.p.p.t.BaseClassFileTransformer       -- Transformer:com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate threw an exception. codeLocation:jar:file:/Users/zhuyuhan/pinpoint_test/demo-caller-1.0.0-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-2.6.3.jar!/ cl:org.springframework.boot.loader.LaunchedURLClassLoader@4102b1b1 ctxCl:org.springframework.boot.loader.LaunchedURLClassLoader@4102b1b1 agentCl:ParallelClassLoader@713338599{name='pinpoint.agent'} Cause:Fail to invoke constructor: public cn.polarismesh.agent.adapter.spring.cloud.interceptor.PolarisAgentPropertiesInterceptor(), arguments: []
com.navercorp.pinpoint.exception.PinpointException: Fail to invoke constructor: public cn.polarismesh.agent.adapter.spring.cloud.interceptor.PolarisAgentPropertiesInterceptor(), arguments: []
	at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.byConstructor(AutoBindingObjectFactory.java:102) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.createInstance(AutoBindingObjectFactory.java:82) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at com.navercorp.pinpoint.profiler.interceptor.factory.AnnotatedInterceptorFactory.newInterceptor(AnnotatedInterceptorFactory.java:123) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.createInterceptor(ASMMethod.java:146) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.newInterceptor(ASMMethod.java:138) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at com.navercorp.pinpoint.profiler.instrument.ASMMethod.addInterceptor(ASMMethod.java:204) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at cn.polarismesh.agent.adapter.spring.cloud.PolarisSpringCloud2021Plugin$PolarisAgentPropertiesTransform.doInTransform(PolarisSpringCloud2021Plugin.java:74) ~[pinpoint-spring-cloud-2021-plugin-1.0.0-SNAPSHOT.jar:?]
	at com.navercorp.pinpoint.profiler.plugin.MatchableClassFileTransformerDelegate.transform(MatchableClassFileTransformerDelegate.java:64) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	at com.navercorp.pinpoint.profiler.transformer.BaseClassFileTransformer.transform(BaseClassFileTransformer.java:56) [pinpoint-profiler-2.3.3.jar:2.3.3]
	at com.navercorp.pinpoint.profiler.transformer.DefaultClassFileTransformerDispatcher.transform(DefaultClassFileTransformerDispatcher.java:90) [pinpoint-profiler-2.3.3.jar:2.3.3]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [?:1.8.0_202]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428) [?:1.8.0_202]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_202]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) [?:1.8.0_202]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_202]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) [?:1.8.0_202]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) [?:1.8.0_202]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) [?:1.8.0_202]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) [?:1.8.0_202]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_202]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) [?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_202]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) [demo-caller-1.0.0-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_202]
	at cn.polarismesh.agent.examples.spring.cloud.DiscoveryCallerService.main(DiscoveryCallerService.java:26) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [demo-caller-1.0.0-SNAPSHOT.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [demo-caller-1.0.0-SNAPSHOT.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [demo-caller-1.0.0-SNAPSHOT.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [demo-caller-1.0.0-SNAPSHOT.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_202]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_202]
	at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.byConstructor(AutoBindingObjectFactory.java:100) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	... 32 more
Caused by: java.lang.NoClassDefFoundError: com/netflix/loadbalancer/ServerList
	at cn.polarismesh.agent.adapter.spring.cloud.interceptor.InterceptorFactory.<clinit>(InterceptorFactory.java:23) ~[pinpoint-spring-cloud-2021-plugin-1.0.0-SNAPSHOT.jar:?]
	at cn.polarismesh.agent.adapter.spring.cloud.interceptor.PolarisAgentPropertiesInterceptor.<init>(PolarisAgentPropertiesInterceptor.java:13) ~[pinpoint-spring-cloud-2021-plugin-1.0.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_202]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_202]
	at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.byConstructor(AutoBindingObjectFactory.java:100) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	... 32 more
Caused by: java.lang.ClassNotFoundException: com.netflix.loadbalancer.ServerList
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[demo-caller-1.0.0-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	at cn.polarismesh.agent.adapter.spring.cloud.interceptor.InterceptorFactory.<clinit>(InterceptorFactory.java:23) ~[pinpoint-spring-cloud-2021-plugin-1.0.0-SNAPSHOT.jar:?]
	at cn.polarismesh.agent.adapter.spring.cloud.interceptor.PolarisAgentPropertiesInterceptor.<init>(PolarisAgentPropertiesInterceptor.java:13) ~[pinpoint-spring-cloud-2021-plugin-1.0.0-SNAPSHOT.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_202]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_202]
	at com.navercorp.pinpoint.profiler.objectfactory.AutoBindingObjectFactory.byConstructor(AutoBindingObjectFactory.java:100) ~[pinpoint-profiler-2.3.3.jar:2.3.3]
	... 32 more

**Comment by chineserobin** [comment]
感觉像是类加载器的问题

**Comment by chuntaojun** [comment]
spring-cloud目前我们还在测试中，当前仅支持了dubbo2.7.x以及dubbox的agent接入
